disabled_rules:
    # 비활성화하고 싶은 규칙
    - trailing_whitespace
    - identifier_name
    - line_length
    - type_name
    - legacy_constructor
    - unused_setter_value
    - void_function_in_ternary
    - function_parameter_count
    - function_body_length
    - nesting
    - comment_spacing

opt_in_rules:
    - empty_count
    - empty_string
    - closure_end_indentation
    - let_var_whitespace

included:
    - Spotify-iOS
excluded:
    # AppDelegate, SceneDelegate, config file 무시
    - Spotify-iOS/Application/AppDelegate.swift
    - Spotify-iOS/Application/SceneDelegate.swift
    - Spotify-iOS/Network/Base/Config.swift

file_length:
    warning: 400 # 400줄 넘어가면 에러 입니다 ^_^

force_cast: warning # 강제 캐스팅 에러 입니다 ^^
